### ISSUE TITLE
Select microcontroller

### ISSUE THREAD

**Issue by SammyOina** [nakujaproject/Flight-Control#1]
Keys:
- Speed
- Size
- Interfaces

Deliverable:

- [ ] Presentation
- [ ] Wiki page
- [ ] Link to product page in shop

**Comment by Pancakem** [comment]
Hello @SammyOina. Are there guys on this issue?

**Comment by SammyOina** [comment]
> Hello @SammyOina. Are there guys on this issue?

Yes there are but i can  add you as well

**Comment by TheParadox20** [comment]
The choice of a development board to be used for flight control was based on the following features:

- Number of CPU cores
- CPU architecture
- MC speed
- RAM and Flash memory
- Number of GPIO pins
- Method of programming
- Cost and availability

Factoring the above, the following boards were shortlisted:

1. STM32F103 (Blue pill)
2. ESP32
3. ESP8266
4. Arduino Nano
### Blue pill
The STM32F103C8T6 is a development board developed by STMicroelectronics with an Arm Cortex-M3 as the CPU.
![stm32](https://user-images.githubusercontent.com/34806448/121777553-70eece00-cb9b-11eb-9868-c65ec57eda40.jpeg)


### ESP32
This system on a chip (SoC) microcontroller developed by espressif and uses the Xtensa LX6 CPU. It has the added capability of Wireless connections and has a hall sensor integrated.
<img width="148" alt="esp32" src="https://user-images.githubusercontent.com/34806448/121777569-84019e00-cb9b-11eb-8c95-8e6a73cb21e3.PNG">

### ESP8266
The esp8266 is the predecessor of the ESP32.
![esp8266](https://user-images.githubusercontent.com/34806448/121777584-9380e700-cb9b-11eb-9989-ff63dab62788.jpeg)

### Arduino Nano
This is another board that belongs to the Arduino family. It has an Atmega328P CPU that powers the board
![arduinoNano](https://user-images.githubusercontent.com/34806448/121777595-9c71b880-cb9b-11eb-9677-21f0a5b1f2e4.jpeg)
### The ATmega328P
An alternative to using development boards, a single microcontroller unit may be used. 
![atmega](https://user-images.githubusercontent.com/34806448/121777782-77317a00-cb9c-11eb-903a-3a54b7701448.jpeg)
The Atmega328P is the MCU used in Arduino Uno and Arduino Nano. It may be programmed using an Arduino board then used to control a circuit
### Programminga
All the above boards can be programmed with the Arduino IDE or platformIO and C++ language using Arduino syntax
### Specifications
![specsTable](https://user-images.githubusercontent.com/34806448/121777685-0ab67b00-cb9c-11eb-8629-02fa0d832ec3.jpeg)

**Comment by kimanimichael** [comment]
Thank you @TheParadox20. From your research, ESP32 is our best option.
