### ISSUE TITLE
Review Flight control Computer

### ISSUE THREAD

**Issue by SammyOina** [nakujaproject/Flight-Control#13]
Review:
- [x] Schematic
- [x] PCB

Use Datasheets and other material to review connections prior to PCB order placement
Files: https://github.com/nakujaproject/flight-control-computer
Software: EasyEDA

**Comment by WashingtonKK** [comment]
👍
Seems good. 
Let the rest do the checking too

**Comment by rodneyosodo** [comment]
- @SammyOina provide I2C connections to the telemetry computer
- Power on LED
- For the decoupling capacitors on the VR shouldn't they be two 100uF and 10nF?
- Check the type of switches you have used, how they are positioned on the PCB. Will it be difficult to operate them?
- For the switch debouncing circuit your bounce time is 66.329ms. You can use a 0.1uF cap to achieve up to 1ms bounce time.
- The USB connector place it on the periphery e.g as shown below
 ![image](https://user-images.githubusercontent.com/28790446/146803209-35468057-4cdd-45cb-affa-871735b90589.png)

**Comment by SammyOina** [comment]
> * @SammyOina provide I2C connections to the telemetry computer
> * Power on LED
> * For the decoupling capacitors on the VR shouldn't they be two 100uF and 10nF?
> * Check the type of switches you have used, how they are positioned on the PCB. Will it be difficult to operate them?
> * For the switch debouncing circuit your bounce time is 66.329ms. You can use a 0.1uF cap to achieve up to 1ms bounce time.
> * The USB connector place it on the periphery e.g as shown below
>   ![image](https://user-images.githubusercontent.com/28790446/146803209-35468057-4cdd-45cb-affa-871735b90589.png)

@0x6f736f646f for telemetry we were providing communication via UART, is I2c Preferred for telemetry?

**Comment by rodneyosodo** [comment]
it is faster

**Comment by SammyOina** [comment]
> * @SammyOina provide I2C connections to the telemetry computer
> * Power on LED
> * For the decoupling capacitors on the VR shouldn't they be two 100uF and 10nF?
> * Check the type of switches you have used, how they are positioned on the PCB. Will it be difficult to operate them?
> * For the switch debouncing circuit your bounce time is 66.329ms. You can use a 0.1uF cap to achieve up to 1ms bounce time.
> * The USB connector place it on the periphery e.g as shown below
>   ![image](https://user-images.githubusercontent.com/28790446/146803209-35468057-4cdd-45cb-affa-871735b90589.png)

I have changed the capacitors on the VR and the switches

**Comment by SammyOina** [comment]
> it is faster

Ok, we've switched from serial to I2C

**Comment by SammyOina** [comment]
> * @SammyOina provide I2C connections to the telemetry computer
> * Power on LED
> * For the decoupling capacitors on the VR shouldn't they be two 100uF and 10nF?
> * Check the type of switches you have used, how they are positioned on the PCB. Will it be difficult to operate them?
> * For the switch debouncing circuit your bounce time is 66.329ms. You can use a 0.1uF cap to achieve up to 1ms bounce time.
> * The USB connector place it on the periphery e.g as shown below
>   ![image](https://user-images.githubusercontent.com/28790446/146803209-35468057-4cdd-45cb-affa-871735b90589.png)

Power On Led added

**Comment by SammyOina** [comment]
Switches moved
![Screenshot 2021-12-29 202331](https://user-images.githubusercontent.com/44265300/147688260-91e775ba-c1c1-43a9-a71a-fbf6f89733fb.png)
Usb moved further
![Screenshot 2021-12-29 202418](https://user-images.githubusercontent.com/44265300/147688278-768b9191-a9f0-4ee0-8d97-2a6259560f1c.png)

**Comment by Hokkyokuse1** [comment]
still a noob at easyeda, but from what I've been able to make sense of, it seems good

**Comment by kimanimichael** [comment]
Since you still have a lot of space I'd advise you to expose rx&tx pins for redundacy purposes.

**Comment by SammyOina** [comment]
> Since you still have a lot of space I'd advise you to expose rx&tx pins for redundacy purposes.

Will do
